FROM php:7.3-fpm-alpine
LABEL maintainer="Y.Sakai @ Bluemoon inc."

ADD     http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz /tmp/

RUN     apk update                       && \
        \
        apk upgrade                      && \
        \
        docker-php-source extract        && \
        \
        apk add --no-cache                  \
            --virtual .build-dependencies   \
                $PHPIZE_DEPS                \
                zlib-dev                    \
                cyrus-sasl-dev              \
                git                         \
                autoconf                    \
                g++                         \
                libtool                     \
                make                        \
                automake                    \
                pcre-dev                 && \
        \
        apk add --no-cache                  \
            gettext                         \
            tini                            \
            libintl                         \
            icu                             \
            icu-dev                         \
            libxml2-dev                     \
            php-soap                        \
            freetype-dev                    \
            libjpeg-turbo-dev               \
            libpng-dev                      \
            gmp                             \
            gmp-dev                         \
            libmemcached-dev                \
            imagemagick-dev                 \
            libssh2                         \
            libssh2-dev                     \
            libxslt-dev                     \
            zip                             \
            libzip-dev                      \
            unzip
#
# comment out 12/31/2019
#   apk add --no-cache icu-l\
#
RUN set -x && \
  apk add --no-cache --virtual build-dependencies && \
  NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) && \
  docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && \
  docker-php-ext-install -j${NPROC} intl && \
  docker-php-ext-install -j${NPROC} mysqli && \
  docker-php-ext-install -j${NPROC} pdo_mysql && \
  docker-php-ext-install -j${NPROC} pdo && \
  docker-php-ext-install -j${NPROC} mbstring && \
  docker-php-ext-install -j${NPROC} bcmath && \
  docker-php-ext-install -j${NPROC} gd && \
  docker-php-ext-install -j${NPROC} xml && \
  docker-php-ext-install -j${NPROC} soap && \
  docker-php-ext-install -j${NPROC} xsl && \
  docker-php-ext-install -j${NPROC} zip && \
  apk del --no-cache --purge build-dependencies && \
  rm -rf /tmp/pear

## blackfire
RUN apk add --no-cache gpgme
RUN curl -A "Docker" -o /usr/local/lib/php/extensions/no-debug-non-zts-20180731/blackfire.so -D - -L -s https://packages.blackfire.io/binaries/blackfire-php/1.29.6/blackfire-php-alpine_amd64-php-73.so \
    && chmod +x /usr/local/lib/php/extensions/no-debug-non-zts-20180731/blackfire.so
RUN mkdir /var/run/blackfire
#RUN version=$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;") \
#    && curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/alpine/amd64/$version \
#    && mkdir -p /tmp/blackfire \
#    && tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp/blackfire \
#    && mv /tmp/blackfire/blackfire-*.so $(php -r "echo ini_get('extension_dir');")/blackfire.so \
#    && printf "extension=blackfire.so\nblackfire.agent_socket=tcp://blackfire:8707\n" > $PHP_INI_DIR/conf.d/blackfire.ini \
#    && rm -rf /tmp/blackfire /tmp/blackfire-probe.tar.gz
#
## For mail catcher
RUN apk --no-cache --update add \
    libstdc++ \
    build-base \
    openssl-dev \
    sqlite \
    sqlite-dev \
    ruby-rdoc \
    ruby-dev && \
    gem install mailcatcher -N

## copy php.ini
ADD php.ini /usr/local/etc/php/php.ini

RUN chmod -R 777 /var/www/html

## set user
RUN set -x && \
  deluser www-data && \
  addgroup -g 50 -S www-data && \
  adduser -u 1000 -D -S -G www-data www-data

